export { Button } from "./Button";
export { Footer } from "./Footer";
export { Game } from "./Game";
export { Guess } from "./Guess";
export { Header } from "./Header";
export { InfoPopUp } from "./InfoPopUp";
export { RandomPopUp } from "./RandomPopUp";
export { Player } from "./Player";
export { Result } from "./Result";
export { Search } from "./Search";
export { WarningPopUp } from "./WarningPopUp"
export { YouTube } from "./YouTube";
